# Generated by Django 5.1.6 on 2025-05-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='user_email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_role',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
