# Generated by Django 5.1.6 on 2025-05-22 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_user_email_ticket_user_location_and_more'),
    ]

    operations = [
    ]
