# Generated by Django 5.1.6 on 2025-05-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_extract_user_info_from_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='user_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
